POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJlbiIsImlkIjoiNjI4NDlkYjQ4NTBiZWNlYTllZmQ3MmNkIiwiaWF0IjoxNjUyODU4NTAxLCJleHAiOjE2NTI4NjIxMDF9.h1-1ECs4OPumvO9hB7DEgqg5J2RHku6X03ZhL9aCY98

{
  "title": "New Post 2",
  "author": "ben",
  "url": "http://localhost",
  "likes": 1001
}

###

# no likes
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "no likes",
  "author": "Anna",
  "url": "http://localhost"
}

###

# no title
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "Anna",
  "url": "http://localhost"
}

###

# no url
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "no url",
  "author": "Anna"
}